########################################
#               AllCops                #
########################################
AllCops:
  TargetRubyVersion: 2.6.3

########################################
#               Metrics                #
########################################
Metrics/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 16

########################################
#                Style                 #
########################################
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

########################################
#               Layout                 #
########################################
Layout/IndentationConsistency:
  EnforcedStyle: rails
